services:
  backend:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app # Maps code for live updates
    env_file:
      - ./django/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./nextjs:/app # Maps code for live updates
      - /app/node_modules # Maps code for live updates
      - /app/.next # Maps code for live updates
    env_file:
      - ./nextjs/.env
    networks:
      - app-network

networks:
  app-network:
