import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

import { Toaster } from "@/components/ui/sonner";
import Providers from "./providers";
import Footer from "@/components/common/footer/Footer";
import { NavigationMenuComp } from "@/components/common/nav/NavigationMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth min-h-screen`}
      >
        <Providers>
          <NavigationMenuComp />
          <main className="min-h-screen">{children}</main>
          <Toaster />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
